import {
    AiOutlineSearch,
    BiCopy,
    BiDownload,
    BiUpload, CgCalendarToday, FaRegFolderOpen,
    FiArrowDown,
    FiArrowUp, HiOutlineDocumentText,
    ImPrinter,
    IoFilterOutline, IoMailOutline,
    IoMdClose,
    IoMdOpen,
    MdDone,
    MdModeEdit,
    MdRefresh,
    RiAddFill,
    RiDeleteBin4Line,
    VscChevronDown, VscChevronLeft, VscChevronRight, VscChevronUp,
} from "react-icons/all";

export const CommonIcons = {
    edit: MdModeEdit,
    delete: RiDeleteBin4Line,
    add: RiAddFill,
    close: IoMdClose,
    chevronDown: VscChevronDown,
    chevronUp: VscChevronUp,
    chevronLeft: VscChevronLeft,
    chevronRight: VscChevronRight,
    download: BiDownload,
    upload: BiUpload,
    print: ImPrinter,
    copy: BiCopy,
    openInNewWindow: IoMdOpen,
    search: AiOutlineSearch,
    check: MdDone,
    up: FiArrowUp,
    down: FiArrowDown,
    filter: IoFilterOutline,
    refresh: MdRefresh,
    mail: IoMailOutline,
    folder: FaRegFolderOpen,
    document: HiOutlineDocumentText,
    calendar: CgCalendarToday
};
