import {
    AiOutlineInfoCircle,
    AiOutlineSearch,
    BiCopy,
    BiDownload,
    BiExport,
    BiImport,
    BiUpload,
    BsCalendar,
    BsList,
    CgCalendarToday,
    FaRegFolderOpen,
    FiArrowDown,
    FiArrowUp,
    HiOutlineDocumentText,
    HiOutlineSave,
    ImPrinter,
    IoFilterOutline,
    IoMailOutline,
    IoMdClose,
    IoMdOpen,
    MdDone,
    MdModeEdit,
    MdRefresh,
    RiAddFill,
    RiDeleteBin4Line,
    RiHistoryFill,
    RiShoppingCartLine,
    VscChevronDown,
    VscChevronLeft,
    VscChevronRight,
    VscChevronUp,
} from "react-icons/all";

export const CommonIcons = {
    edit: MdModeEdit,
    delete: RiDeleteBin4Line,
    add: RiAddFill,
    close: IoMdClose,
    chevronDown: VscChevronDown,
    chevronUp: VscChevronUp,
    chevronLeft: VscChevronLeft,
    chevronRight: VscChevronRight,
    download: BiDownload,
    upload: BiUpload,
    import: BiImport,
    export: BiExport,

    print: ImPrinter,
    copy: BiCopy,
    openInNewWindow: IoMdOpen,
    search: AiOutlineSearch,
    check: MdDone,
    up: FiArrowUp,
    down: FiArrowDown,
    filter: IoFilterOutline,
    refresh: MdRefresh,
    mail: IoMailOutline,
    folder: FaRegFolderOpen,
    document: HiOutlineDocumentText,
    calendar: BsCalendar,

    back: VscChevronLeft,
    save: HiOutlineSave,
    list: BsList,
    cart: RiShoppingCartLine,
    info: AiOutlineInfoCircle,
    history: RiHistoryFill,
};
