export const applyButtons: string;
export const button: string;
export const buttonPanel: string;
export const description: string;
export const fieldBlock: string;
export const filterType: string;
export const main: string;
export const title: string;
export const valueRow: string;
