name: Webpage build
on:
  push:
    branches: neo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}    
      - run: yarn install
      - run: yarn build-storybook
      - uses: peaceiris/actions-gh-pages@v3
        name: Deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
    
    
        

  
